### ISSUE TITLE
菜鸟请教代码相关问题

### ISSUE THREAD

**Issue by Aphroditefang** [zhangtianle/jd#1]
请问，这个代码应该主要看tl还是qx中的代码呢？然后这些代码应该怎样运行呢。原谅我是一个菜鸟

**Comment by zhangtianle** [comment]
tl 是我写的代码，qx是我队友的代码。  
tl 文件夹里面，我更新了各个文件的作用 https://github.com/zhangtianle/jd/blob/master/tl/src/README.md   
先运行 src 下面的 DataAnalysis.py 生成各类特征，并保存到文件中用于下一步的训练  
再运行 src 下面的 Main.py 根据上一步得到的特征，预测结果。
