### ISSUE TITLE
文件遗漏问题~

### ISSUE THREAD

**Issue by Zoieee** [zhangtianle/jd#2]
您好，请问qx GetTestData 和Main 代码下 的Loan_Forecasting_Upload_Sample.csv这个文件是自己后期处理的吗~运行的时候没找着，在您提供的数据源下没有这份数据呢，请问是怎么做的呢？谢谢

**Comment by zhangtianle** [comment]
谢谢！这是赛题给的数据，已更新
链接：https://pan.baidu.com/s/1b-USsanDScR0CRoHABfNGQ 密码：l94v

**Comment by Zoieee** [comment]
非常谢谢！！~
